config/routes.rb
Rails.application.routes.draw do
  resources :chats
 root "posts#home"
 get 'users/:id/profile', to: 'users#profile', as: 'user_profile'
  devise_for :users, controllers: {
    registrations: 'users/registrations' ,
    sessions: 'users/sessions' ,
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :users do
    post 'follow',   to: 'socializations#follow'
    post 'unfollow', to: 'socializations#unfollow'
    post 'like', to: 'socializations#like'
    delete 'unlike', to: 'socializations#unlike'
  end
  
  resources :profile

  resources :posts do
    member do
      post 'like', to: 'socializations#like'
      delete 'unlike', to: 'socializations#unlike' 
    end
    resources :comments, only: [:create, :destroy]
  end
resources :chats do
  resources :messages
end
match '*path' => redirect('/'), via: :get
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  validates_presence_of :body
  validates_presence_of :commenter
  validates :body, length: { maximum: 40 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    @comment.commenter = current_user.full_name
    if @comment.save
      redirect_to post_path(@post), notice: 'Comment was successfully created.'
    else
      redirect_to post_path(@post), alert: "Error: #{@comment.errors.full_messages.join(', ')}"
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
      redirect_to post_path(@post)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="comment">
  <div class="post-info">
    <p class="commenter">
      <strong><%= comment.commenter %></strong>
      <span class="comment-body"><%= comment.body %></span>
    </p>
    <div class="about">
      <span class="time-ago">
        <%= time_ago_in_words(comment.created_at) %> ago
      </span>
  <% if comment.commenter == current_user.full_name %>
  <div class="delete-btn">
    <%= button_to 'Delete', post_comment_path(@post, comment), method: :delete,
                  data: { confirm: "Are you sure?" } %>
  </div>
<% end %>
</div>
    </div>
  </div>

app/views/comments/_form.html.erb
<%= form_with model: [ post, post.comments.build ] do |form| %>
 <p>
    <%= form.hidden_field :commenter %><br> 
  </p>
    <%= form.textarea :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>