config/routes.rb
Rails.application.routes.draw do
  resources :chats
 root "posts#home"
 get 'users/:id/profile', to: 'users#profile', as: 'user_profile'
  devise_for :users, controllers: {
    registrations: 'users/registrations' ,
    sessions: 'users/sessions' ,
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :users do
    post 'follow',   to: 'socializations#follow'
    post 'unfollow', to: 'socializations#unfollow'
    post 'like', to: 'socializations#like'
    delete 'unlike', to: 'socializations#unlike'
  end
  
  resources :profile

  resources :posts do
    member do
      post 'like', to: 'socializations#like'
      delete 'unlike', to: 'socializations#unlike' 
    end
    resources :comments, only: [:create, :destroy]
  end
resources :chats do
  resources :messages
end
match '*path' => redirect('/'), via: :get
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/chat.rb
class Chat < ApplicationRecord
  has_many :messages,  dependent: :destroy
  validates :name,  uniqueness: true
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :set_chat, only: %i[ show edit update destroy ]
  include ActionView::RecordIdentifier

  # GET /chats or /chats.json
  def index
    @chats = Chat.all
  end

  # GET /chats/1 or /chats/1.json
  def show
  end

  # GET /chats/new
  def new
    @chat = Chat.new
  end

  # GET /chats/1/edit
  def edit
  end

  # POST /chats or /chats.json
  def create
    @chat = Chat.new(chat_params)

    respond_to do |format|
      if @chat.save
        format.html { redirect_to @chat }
        format.json { render :show, status: :created, location: @chat }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chats/1 or /chats/1.json
  def update
    respond_to do |format|
      if @chat.update(chat_params)
        format.html { redirect_to @chat, notice: "Chat was successfully updated." }
        format.json { render :show, status: :ok, location: @chat }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chats/1 or /chats/1.json
  def destroy
    @chat.destroy!

    respond_to do |format|
      format.html { redirect_to chats_path, status: :see_other, notice: "Chat was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chat
      @chat = Chat.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def chat_params
      params.expect(chat: [ :name ])
    end
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/views/chats/_chat.html.erb
<div id="<%= dom_id chat %>">
  <p>
    <strong>Name:</strong>
    <%= chat.name %>
  </p>

</div>

app/views/chats/_form.html.erb
<%= form_with(model: chat) do |form| %>
  <% if chat.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(chat.errors.count, "error") %> prohibited this chat from being saved:</h2>

      <ul>
        <% chat.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

<div class="save-btn">
  <%= form.submit "Save Chat", class: "chat-btn" %>
</div>

<% end %>

app/views/chats/edit.html.erb
<% content_for :title, "Editing chat" %>

<h1>Editing chat</h1>
<%= turbo_frame_tag "chat" do%>
<%= render "form", chat: @chat %>

<br>
<%end%>

<div>
  <%= link_to "Show this chat", @chat %> |
  <%= link_to "Back to chats", chats_path %>
</div>

app/views/chats/index.html.erb
<% content_for :title, "Chats" %>

<h1>Chats</h1>

<div id="chats" class="links-too-b">
  <% @chats.each do |chat| %>
    <%= render chat %>
    <p>
      <%= link_to "Show this chat", chat , class: "chat-btn" %>
    </p>
  <% end %>
</div>

<%= button_to "New chat", new_chat_path,  method: :get, class: "messenger-btn"  %><br>
<%= button_to "Main", root_path,  method: :get, class: "messenger-btn"  %>

app/views/chats/new.html.erb
<% content_for :title, "New chat" %>

<h1>New chat</h1>

<%= render "form", chat: @chat %>

<br>

<div>
  <%= link_to "Back to chats", chats_path , class: "chat-btn"  %>
</div>

app/views/chats/show.html.erb
<%= turbo_stream_from @chat%>
<%= turbo_frame_tag "chat" do%>
<%= render @chat %>
<div class="links-too-b">
 <%= link_to "Back to chats", chats_path, class: "chat-btn", "data-turbo-frame": "_top" %>
<%= link_to "Edit this chat", edit_chat_path(@chat), class: "chat-btn" %>
<%= button_to "Destroy this chat", @chat, method: :delete, class: "chat-btn", "data-turbo-frame": "_top" %>
</div>
<%end%>


<div id="messages">
  <%= render @chat.messages%>
  </div>

   <%= turbo_frame_tag "new_message" , src: new_chat_message_path(@chat), target: "_top"%>