config/routes.rb
Rails.application.routes.draw do
  resources :chats
 root "posts#home"
 get 'users/:id/profile', to: 'users#profile', as: 'user_profile'
  devise_for :users, controllers: {
    registrations: 'users/registrations' ,
    sessions: 'users/sessions' ,
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :users do
    post 'follow',   to: 'socializations#follow'
    post 'unfollow', to: 'socializations#unfollow'
    post 'like', to: 'socializations#like'
    delete 'unlike', to: 'socializations#unlike'
  end
  
  resources :profile

  resources :posts do
    member do
      post 'like', to: 'socializations#like'
      delete 'unlike', to: 'socializations#unlike' 
    end
    resources :comments, only: [:create, :destroy]
  end
resources :chats do
  resources :messages
end
match '*path' => redirect('/'), via: :get
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, length: { minimum: 10 }
  validates :content, presence: true
  belongs_to :user, foreign_key: "user_id"
  acts_as_likeable
  has_many :comments, dependent: :destroy
  has_rich_text :content
  has_one_attached :avatar
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  def index
    @posts = Post.includes(:user).order(created_at: :desc)
  end

  def new
    @post = Post.new
  end
  def home
    @posts = Post.includes(:user).order(created_at: :desc)
    @user =  current_user
    @followers =  @user.followers(User)
    @other_users = User.all.where("id != ?", current_user.id).where.not(id: current_user.followees(User).pluck(:id))
    @followees = @user.followees(User)
  end

  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
    if @post.save
      flash[:success] = 'Post successfully created'
      format.turbo_stream
    else
       flash[:error] = 'Something went wrong'
       format.html { render :new, status: :unprocessable_entity }

    end
    end
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments.order(created_at: :desc)
  end


  def destroy
  @post = Post.find(params[:id])
  @post.destroy
    redirect_to root_path
  end


  private

  def post_params
    params.require(:post).permit(:content)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.erb
<div class="post-content">
  <div class="post-info">
    <p>
      <strong><%= link_to post.user.full_name, profile_path(post.user), class: "no-decoration" %></strong> 
      • 
      <%= time_ago_in_words(post.created_at) %> ago
    </p>
    <p><%= post.content %></p>
  </div>

  <%= link_to 'View Post', post_path(post), class: "view-post-link" %>

  <div class="resources-post">
    <% if post.user.id == current_user.id %> 
      <div class="delete-btn">
        <%= button_to 'Delete', post_path(post), method: :delete, 
                      data: { turbo: "false", confirm: "Delete this post?" } %>
      </div>
    <% end %>

    <%= render partial: 'likes/like_section', locals: { post: post } %>

    <p><%= post.comments.count %> <%= post.comments.count == 1 ? 'comment' : 'comments' %></p>
  </div>
</div>

app/views/posts/create.turbo_stream.erb
<%= turbo_stream.prepend "posts", partial: "post", locals: { post: @post } %>

app/views/posts/home.html.erb
<div class="the-container">
  <nav class="navbar">
    <a href="/" class="navbar-logo">OdinBook</a>
    <div class="navbar-actions">
   <div class="chats-btn">
  <%= button_to "chats!", chats_path, method: :get, class: "messenger-btn" %>
</div>
      <% if current_user.avatar_url != nil %>
        <%= link_to profile_path(current_user.id), style: "display: inline-block; text-decoration: none;" do %>
          <%= image_tag(
            current_user.avatar_url, 
            style: "width: 50px; height: 50px; border-radius: 50%; border: 2px solid linear-gradient(45deg, #f09433, #e6683c, #dc2743, #cc2366, #bc1888); box-sizing: border-box; padding: 2px; transition: transform 0.3s, border-color 0.3s;"
          ) %>
        <% end %>
      <% else %>
        <%= link_to profile_path(current_user.id), style: "display: inline-block; text-decoration: none;" do %>
          <%= image_tag("avatar.png", 
            style: "width: 50px; height: 50px; border-radius: 50%; border: 2px solid linear-gradient(45deg, #f09433, #e6683c, #dc2743, #cc2366, #bc1888); box-sizing: border-box; padding: 2px; transition: transform 0.3s, border-color 0.3s;"
          ) %>
        <% end %>
      <% end %>

      <style>
        a:hover img {
          transform: scale(1.2); /* Increases size by 20% */
          border-color: #4caf50; /* Changes border to green */
        }
      </style>

      <div class="account-pref">
        <% if current_user %>
          <%= button_to "Logout", destroy_user_session_path, data: {turbo: "false"}, method: :delete %>
        <% else %>
          <%= link_to "Login", new_user_session_path %>
          <%= link_to "Create Account", new_user_registration_path %>
        <% end %>
      </div>
    </div>
  </nav>
</div>

<div class="main-container">
  <div class="left-bar">
    <h3>Followers:<% @followers.each do |i| %></h3>
       <p><%= link_to i.full_name, profile_path(i), class: "no-decoration" %></p>
    <% end %><br>
    <h3>Following:<% @followees.each do |i| %></h3>
       <p><%= link_to i.full_name, profile_path(i), class: "no-decoration"  %></p>
    <% end %><br>
  </div>
  

  <div class="posts-container">
    <div class="self-info"><% if current_user%>
    <h2>Welcome <%=current_user.full_name + "!"|| "back!"%></h2><br> 
    <%= turbo_frame_tag "new_post", src: new_post_path , method: :post%>
    </div>
    <% end %>

  <div class="all-posts" id="posts">
    <% @posts.each do |post| %>
      <div class="post">
        <%= render partial: "post", locals: { post: post } %>
      </div>
    <% end %>
  </div>
</div>

  <div class="right-bar">
  <div class="friends">
      <h3>People you may want to follow:</h3>
      <ul>
        <% @other_users.each do |other_user| %>
          <li>
            <%= link_to other_user.full_name, profile_path(other_user), class: "no-decoration"%> <%= button_to 'Follow', user_follow_path(other_user), method: :post %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<%= turbo_frame_tag "new_post" do %>
  <%= form_with(model: @post, 
                data: {
                  controller: "reset-form",
                  action: "turbo:submit-end->reset-form#reset"
                }) do |form| %>
    <%= form.rich_text_area :content, 
          placeholder: "What are you thinking #{current_user.full_name}?" %>
    <%= form.submit "Post", class: "custom-button" %>
  <% end %>
<% end %>

app/views/posts/show.html.erb
<a href="/" class="show-p-logo">OdinBook</a>

<div class="profile-user-posts">
  <div class="post-user">
    <p class="post-header">
      <strong><%= @post.user.full_name %></strong>
      •
      <span class="post-time"><%= time_ago_in_words(@post.created_at) %> ago</span>
    </p>
    <div class="content-post">
      <p><%= @post.content %></p>
    </div>
  </div>

<h3>Comments</h3>
<%= render @comments %>

<div class="comment-add-sec">
<h2 class="section-title">Add a comment:</h2>
<div class="add-comment">
  <%= render "comments/form", post: @post %>
</div>
</div>